import React, { useState, useRef, useEffect, useMemo } from 'react'
import TopBar from './components/TopBar'
import ConfigSection from './components/ConfigSection'
import ColdEmailTab from './components/tabs/ColdEmailTab'
import ColdCallTab from './components/tabs/ColdCallTab'
import ObjectionTab from './components/tabs/ObjectionTab'
import ResearchTab from './components/tabs/ResearchTab'
import BattlecardTab from './components/tabs/BattlecardTab'
import CompetitiveIntelTab from './components/tabs/CompetitiveIntelTab'
import { callPerplexity } from './api/perplexity'

const TABS = [
  { id: 'email', icon: '📧', label: 'Cold Email Generator' },
  { id: 'call', icon: '📞', label: 'Cold Call Scripts' },
  { id: 'objection', icon: '🛡️', label: 'Objection Handler' },
  { id: 'research', icon: '🔍', label: 'Pre-Call Research' },
  { id: 'battlecard', icon: '⚔️', label: 'Sales Battlecard' },
  { id: 'competitive', icon: '🔎', label: 'Competitive Intel' },
]

const DEFAULT_CONFIG = {
  vertical: '',
  customVertical: '',
  productDescription: '',
  companyWebsite: '',
  anthropicKey: '',
  perplexityKey: '',
}

export default function App() {
  const [config, setConfig] = useState(DEFAULT_CONFIG)
  const [activeTab, setActiveTab] = useState('email')
  const [generatedOutputs, setGeneratedOutputs] = useState({})
  const [companyContext, setCompanyContext] = useState('')
  const [fetchingCompanyContext, setFetchingCompanyContext] = useState(false)
  const configRef = useRef(null)

  // Fetch company context from Perplexity when website + key are both set
  useEffect(() => {
    if (!config.companyWebsite.trim() || !config.perplexityKey.trim()) {
      setCompanyContext('')
      return
    }
    const timer = setTimeout(async () => {
      setFetchingCompanyContext(true)
      try {
        const result = await callPerplexity({
          apiKey: config.perplexityKey,
          query: `What does ${config.companyWebsite} do? What product or service do they sell? Who are their customers? What are their key features and differentiators?`,
        })
        setCompanyContext(result || '')
      } catch {
        setCompanyContext('')
      } finally {
        setFetchingCompanyContext(false)
      }
    }, 800)
    return () => clearTimeout(timer)
  }, [config.companyWebsite, config.perplexityKey])

  // Merge companyContext into config so all tabs receive it
  const configWithContext = useMemo(() => ({
    ...config,
    companyContext,
    fetchingCompanyContext,
  }), [config, companyContext, fetchingCompanyContext])

  const handleMissingKey = () => {
    configRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    if (configRef.current) {
      configRef.current.style.boxShadow = '0 0 0 2px var(--error)'
      setTimeout(() => {
        if (configRef.current) configRef.current.style.boxShadow = ''
      }, 1500)
    }
  }

  const handleDownloadSalesPlay = () => {
    const vertical = config.vertical === 'Custom' ? config.customVertical : config.vertical
    const filename = `${(vertical || 'smb').toLowerCase().replace(/[^a-z0-9]/g, '-')}-sales-play.md`

    const sections = []
    sections.push(`# ${vertical || 'SMB'} Sales Play`)
    sections.push(`*Generated by Orbital SMB Sales Toolkit*\n`)
    sections.push(`**Product:** ${config.productDescription || config.companyWebsite || 'Not specified'}`)
    sections.push(`**Vertical:** ${vertical || 'Not specified'}\n`)
    sections.push('---\n')

    if (generatedOutputs.email) {
      sections.push('## Cold Emails\n')
      sections.push(generatedOutputs.email)
      sections.push('\n---\n')
    }
    if (generatedOutputs.call) {
      sections.push('## Cold Call Script\n')
      sections.push(generatedOutputs.call)
      sections.push('\n---\n')
    }
    if (generatedOutputs.objection) {
      sections.push('## Objection Responses\n')
      sections.push(generatedOutputs.objection)
      sections.push('\n---\n')
    }
    if (generatedOutputs.research) {
      sections.push('## Pre-Call Research Brief\n')
      sections.push(generatedOutputs.research)
      sections.push('\n---\n')
    }
    if (generatedOutputs.battlecard) {
      sections.push('## Sales Battlecard\n')
      sections.push(generatedOutputs.battlecard)
      sections.push('\n---\n')
    }
    if (generatedOutputs.competitive) {
      sections.push('## Competitive Intel Brief\n')
      sections.push(generatedOutputs.competitive)
      sections.push('\n---\n')
    }

    sections.push('\n*Powered by [Orbital](https://www.withorbital.com/?utm_source=smb-toolkit&utm_medium=tool&utm_campaign=sales-play) — SMB Account Intelligence*')

    const content = sections.join('\n')
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  const hasAnyOutput = Object.keys(generatedOutputs).length > 0

  return (
    <div style={{ minHeight: '100vh', backgroundColor: 'var(--bg)' }}>
      <TopBar />

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '32px 24px' }}>
        {/* Config */}
        <ConfigSection config={configWithContext} onChange={setConfig} configRef={configRef} />

        {/* Missing key warning */}
        {!config.anthropicKey && (
          <div style={{
            marginBottom: 24, padding: '12px 18px',
            background: 'rgba(229,169,27,0.1)', border: '1px solid rgba(229,169,27,0.25)',
            borderRadius: 8, fontSize: 13, color: 'var(--warning)',
            display: 'flex', alignItems: 'center', gap: 8,
          }}>
            ⚠️ Add your Anthropic API key above to start generating. Your key is never saved — it lives only in this browser session.
          </div>
        )}

        {/* Tab Navigation */}
        <div style={{ marginBottom: 24 }}>
          <div style={{
            display: 'flex', borderBottom: '1px solid var(--border)',
            overflowX: 'auto', gap: 0,
          }}>
            {TABS.map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 8,
                  padding: '12px 20px',
                  background: 'none', border: 'none', cursor: 'pointer',
                  color: activeTab === tab.id ? 'var(--text-primary)' : 'var(--text-secondary)',
                  borderBottom: activeTab === tab.id ? '2px solid var(--accent)' : '2px solid transparent',
                  marginBottom: '-1px',
                  fontWeight: activeTab === tab.id ? 600 : 400,
                  fontSize: 14,
                  transition: 'all 0.2s ease',
                  whiteSpace: 'nowrap',
                }}
                onMouseEnter={e => {
                  if (activeTab !== tab.id) e.currentTarget.style.color = 'var(--text-primary)'
                }}
                onMouseLeave={e => {
                  if (activeTab !== tab.id) e.currentTarget.style.color = 'var(--text-secondary)'
                }}
              >
                <span style={{ fontSize: 16 }}>{tab.icon}</span>
                <span>{tab.label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Tab Content — all tabs stay mounted to preserve state during generation */}
        <div style={{ minHeight: 400 }}>
          <div style={{ display: activeTab === 'email' ? 'block' : 'none' }}>
            <ColdEmailTab config={configWithContext} onMissingKey={handleMissingKey} />
          </div>
          <div style={{ display: activeTab === 'call' ? 'block' : 'none' }}>
            <ColdCallTab config={configWithContext} onMissingKey={handleMissingKey} />
          </div>
          <div style={{ display: activeTab === 'objection' ? 'block' : 'none' }}>
            <ObjectionTab config={configWithContext} onMissingKey={handleMissingKey} />
          </div>
          <div style={{ display: activeTab === 'research' ? 'block' : 'none' }}>
            <ResearchTab config={configWithContext} onMissingKey={handleMissingKey} />
          </div>
          <div style={{ display: activeTab === 'battlecard' ? 'block' : 'none' }}>
            <BattlecardTab config={configWithContext} onMissingKey={handleMissingKey} />
          </div>
          <div style={{ display: activeTab === 'competitive' ? 'block' : 'none' }}>
            <CompetitiveIntelTab
              config={configWithContext}
              onMissingKey={handleMissingKey}
              onOutputGenerated={text => setGeneratedOutputs(prev => ({ ...prev, competitive: text }))}
            />
          </div>
        </div>

        {/* Download Complete Sales Play */}
        <div style={{ marginTop: 48, padding: '32px', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-card)', textAlign: 'center' }}>
          <div style={{ fontSize: 24, marginBottom: 12 }}>📥</div>
          <h3 style={{ fontWeight: 700, fontSize: 20, marginBottom: 8 }}>Download Complete Sales Play</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: 14, marginBottom: 24, maxWidth: 500, margin: '0 auto 24px' }}>
            Bundle everything you've generated into one document. Switch between tabs, generate your content, then come back here to download it all.
          </p>
          <button
            className="btn btn-primary"
            style={{ maxWidth: 320, margin: '0 auto', fontSize: 15, padding: '14px 32px' }}
            onClick={handleDownloadSalesPlay}
          >
            ⬇️ Download Sales Play
          </button>
          {!hasAnyOutput && (
            <p style={{ marginTop: 12, fontSize: 12, color: 'var(--text-secondary)', opacity: 0.7 }}>
              Generate content in the tabs above first, then download everything as a single .md file.
            </p>
          )}
        </div>

        {/* Footer */}
        <div style={{ marginTop: 48, textAlign: 'center', paddingBottom: 32 }}>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', opacity: 0.6 }}>
            Built for sales teams selling to small businesses.{' '}
            <a href="https://www.withorbital.com/?utm_source=smb-toolkit&utm_medium=tool&utm_campaign=footer" target="_blank" rel="noopener noreferrer">
              Powered by Orbital
            </a>
            .
          </div>
        </div>
      </div>
    </div>
  )
}
